---
abstract: 'README.mkdn in the project root with links to Meta::CPAN'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MarkdownInRoot
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Dist::Zilla::Plugin::MarkdownInRoot:
    file: lib/Dist/Zilla/Plugin/MarkdownInRoot.pm
    version: v0.1.3
  Dist::Zilla::Plugin::MarkdownInRoot::WithMetaLinks:
    file: lib/Dist/Zilla/Plugin/MarkdownInRoot/WithMetaLinks.pm
    version: v0.1.2
requires:
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.120120
  Moose: 2.0802
  Pod::Markdown: 1.322
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-MarkdownInRoot
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.1.3
